"""Unit tests for the operator UI job runner CLI dispatch."""

from __future__ import annotations

import json
import signal
import sys as _sys
import tempfile
import unittest
from pathlib import Path
from subprocess import CompletedProcess
from unittest.mock import patch

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in _sys.path:
    _sys.path.insert(0, str(_PROJECT_ROOT))


class JobRunnerDispatchTests(unittest.TestCase):
    def test_tushare_provider_mode_launches_existing_ingest_cli(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "qlib_provider"
            output_dir.mkdir()
            (output_dir / "calendars").mkdir()
            job_dir.joinpath("config.yaml").write_text(
                f"output_dir: {output_dir}\n"
                "start_date: '2025-01-01'\n"
                "end_date: '2025-01-31'\n"
                "data_adjust_mode: pre_adjusted\n",
                encoding="utf-8",
            )

            with patch("subprocess.run") as mock_run:
                mock_run.return_value = CompletedProcess(args=[], returncode=0)
                main([str(job_dir), "tushare_provider"])

            cmd = mock_run.call_args[0][0]
            kwargs = mock_run.call_args.kwargs
            self.assertIn("scripts/ingest_tushare_qlib_provider.py", cmd)
            self.assertFalse(kwargs["shell"])
            self.assertIn(str(Path(__file__).resolve().parents[2]), kwargs["env"]["PYTHONPATH"])
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "success")
            self.assertEqual(data["run_dir"], str(output_dir))

    def test_output_dir_is_read_with_yaml_parser(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "quoted qlib provider"
            output_dir.mkdir()
            (output_dir / "calendars").mkdir()
            job_dir.joinpath("config.yaml").write_text(
                f"output_dir: '{output_dir}' # generated by UI\n"
                "start_date: '2025-01-01'\n"
                "end_date: '2025-01-31'\n"
                "data_adjust_mode: pre_adjusted\n",
                encoding="utf-8",
            )

            with patch("subprocess.run") as mock_run:
                mock_run.return_value = CompletedProcess(args=[], returncode=0)
                main([str(job_dir), "tushare_provider"])

            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["run_dir"], str(output_dir))

    def test_pipeline_mode_copies_exact_config_to_run_dir(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "pipeline_output"
            run_dir = output_dir / "runs" / "pipeline_run"
            run_dir.mkdir(parents=True)
            config_text = (
                f"output_dir: '{output_dir}' # exact UI config\n"
                "provider_uri: 'D:/qlib_data/my_cn_data'\n"
            )
            job_dir.joinpath("config.yaml").write_text(config_text, encoding="utf-8")

            with patch("subprocess.run") as mock_run:
                mock_run.return_value = CompletedProcess(args=[], returncode=0)
                main([str(job_dir), "pipeline"])

            copied = run_dir.joinpath("config.yaml").read_text(encoding="utf-8")
            self.assertEqual(copied, config_text)
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["run_dir"], str(run_dir))

    def test_failed_pipeline_does_not_bind_or_overwrite_existing_run_dir(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "pipeline_output"
            old_run_dir = output_dir / "runs" / "old_pipeline_run"
            old_run_dir.mkdir(parents=True)
            old_config = "provider_uri: old\n"
            old_run_dir.joinpath("config.yaml").write_text(old_config, encoding="utf-8")
            job_dir.joinpath("config.yaml").write_text(
                f"output_dir: '{output_dir}'\nprovider_uri: new\n",
                encoding="utf-8",
            )

            with patch("subprocess.run") as mock_run:
                mock_run.return_value = CompletedProcess(args=[], returncode=2)
                main([str(job_dir), "pipeline"])

            copied = old_run_dir.joinpath("config.yaml").read_text(encoding="utf-8")
            self.assertEqual(copied, old_config)
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "failed")
            self.assertNotIn("run_dir", data)

    def test_stop_signal_handler_marks_job_stopped(self) -> None:
        import web.operator_ui.job_runner as job_runner

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            job_runner._ACTIVE_JOB_DIR = job_dir

            with self.assertRaises(SystemExit) as exc:
                job_runner._handle_stop_signal(signal.SIGTERM, None)

            self.assertEqual(exc.exception.code, 128 + signal.SIGTERM)
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "stopped")
            self.assertEqual(data["stop_signal"], signal.SIGTERM)
            self.assertIsNotNone(data["ended_at"])


if __name__ == "__main__":
    unittest.main()
