"""Unit tests for the operator UI job runner CLI dispatch."""

from __future__ import annotations

import json
import signal
import subprocess
import sys as _sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in _sys.path:
    _sys.path.insert(0, str(_PROJECT_ROOT))


class JobRunnerDispatchTests(unittest.TestCase):
    def test_tushare_provider_mode_launches_existing_ingest_cli(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "qlib_provider"
            output_dir.mkdir()
            (output_dir / "calendars").mkdir()
            job_dir.joinpath("config.yaml").write_text(
                f"output_dir: {output_dir}\n"
                "start_date: '2025-01-01'\n"
                "end_date: '2025-01-31'\n"
                "data_adjust_mode: pre_adjusted\n",
                encoding="utf-8",
            )

            with patch("subprocess.Popen") as mock_popen:
                mock_proc = mock_popen.return_value
                mock_proc.wait.return_value = 0
                main([str(job_dir), "tushare_provider"])

            cmd = mock_popen.call_args[0][0]
            kwargs = mock_popen.call_args.kwargs
            self.assertIn("scripts/ingest_tushare_qlib_provider.py", cmd)
            self.assertFalse(kwargs["shell"])
            self.assertIn(str(Path(__file__).resolve().parents[2]), kwargs["env"]["PYTHONPATH"])
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "success")
            self.assertEqual(data["run_dir"], str(output_dir))

    def test_output_dir_is_read_with_yaml_parser(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "quoted qlib provider"
            output_dir.mkdir()
            (output_dir / "calendars").mkdir()
            job_dir.joinpath("config.yaml").write_text(
                f"output_dir: '{output_dir}' # generated by UI\n"
                "start_date: '2025-01-01'\n"
                "end_date: '2025-01-31'\n"
                "data_adjust_mode: pre_adjusted\n",
                encoding="utf-8",
            )

            with patch("subprocess.Popen") as mock_popen:
                mock_proc = mock_popen.return_value
                mock_proc.wait.return_value = 0
                main([str(job_dir), "tushare_provider"])

            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["run_dir"], str(output_dir))

    def test_pipeline_mode_copies_exact_config_to_run_dir(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "pipeline_output"
            run_dir = output_dir / "runs" / "pipeline_run"
            run_dir.mkdir(parents=True)
            config_text = (
                f"output_dir: '{output_dir}' # exact UI config\n"
                "provider_uri: 'D:/qlib_data/my_cn_data'\n"
            )
            job_dir.joinpath("config.yaml").write_text(config_text, encoding="utf-8")

            with patch("subprocess.Popen") as mock_popen:
                mock_proc = mock_popen.return_value
                mock_proc.wait.return_value = 0
                main([str(job_dir), "pipeline"])

            copied = run_dir.joinpath("config.yaml").read_text(encoding="utf-8")
            self.assertEqual(copied, config_text)
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["run_dir"], str(run_dir))

    def test_failed_pipeline_does_not_bind_or_overwrite_existing_run_dir(self) -> None:
        from web.operator_ui.job_runner import main

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            output_dir = job_dir / "pipeline_output"
            old_run_dir = output_dir / "runs" / "old_pipeline_run"
            old_run_dir.mkdir(parents=True)
            old_config = "provider_uri: old\n"
            old_run_dir.joinpath("config.yaml").write_text(old_config, encoding="utf-8")
            job_dir.joinpath("config.yaml").write_text(
                f"output_dir: '{output_dir}'\nprovider_uri: new\n",
                encoding="utf-8",
            )

            with patch("subprocess.Popen") as mock_popen:
                mock_proc = mock_popen.return_value
                mock_proc.wait.return_value = 2
                main([str(job_dir), "pipeline"])

            copied = old_run_dir.joinpath("config.yaml").read_text(encoding="utf-8")
            self.assertEqual(copied, old_config)
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "failed")
            self.assertNotIn("run_dir", data)

    def test_stop_signal_handler_marks_job_stopped(self) -> None:
        import web.operator_ui.job_runner as job_runner

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            job_runner._ACTIVE_JOB_DIR = job_dir
            job_runner._ACTIVE_CHILD_PROCESS = None  # no child for this case

            with self.assertRaises(SystemExit) as exc:
                job_runner._handle_stop_signal(signal.SIGTERM, None)

            self.assertEqual(exc.exception.code, 128 + signal.SIGTERM)
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "stopped")
            self.assertEqual(data["stop_signal"], signal.SIGTERM)
            self.assertIsNotNone(data["ended_at"])

    # ----------------------------------------------------------------
    # Regression for bug.md P1-4: the SIGTERM handler previously
    # raised ``SystemExit`` without touching the training subprocess.
    # ``subprocess.run`` had no caller-visible Popen handle, so on
    # Linux the child re-parented to init; on Windows it just kept
    # running. After the fix, the handler ``terminate()`` s the child
    # before exiting.
    # ----------------------------------------------------------------

    def test_stop_signal_handler_terminates_active_child_process(self) -> None:
        import web.operator_ui.job_runner as job_runner

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            job_runner._ACTIVE_JOB_DIR = job_dir
            # Simulate a live child training process: poll() returns
            # None (still running), wait() succeeds after terminate().
            fake_child = MagicMock()
            fake_child.poll.return_value = None
            fake_child.wait.return_value = 0
            job_runner._ACTIVE_CHILD_PROCESS = fake_child

            try:
                with self.assertRaises(SystemExit):
                    job_runner._handle_stop_signal(signal.SIGTERM, None)
            finally:
                job_runner._ACTIVE_CHILD_PROCESS = None

            fake_child.terminate.assert_called_once()
            fake_child.wait.assert_called()
            data = json.loads(job_dir.joinpath("job.json").read_text(encoding="utf-8"))
            self.assertEqual(data["status"], "stopped")

    def test_stop_signal_handler_falls_back_to_kill_on_timeout(self) -> None:
        """If the child ignores ``terminate()`` and ``wait()`` times
        out, the handler must escalate to ``kill()`` rather than
        leaking the process."""
        import web.operator_ui.job_runner as job_runner

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            job_runner._ACTIVE_JOB_DIR = job_dir
            fake_child = MagicMock()
            fake_child.poll.return_value = None
            # First wait() (after terminate) raises TimeoutExpired,
            # second wait() (after kill) returns normally.
            fake_child.wait.side_effect = [
                subprocess.TimeoutExpired(cmd="python", timeout=5.0),
                0,
            ]
            job_runner._ACTIVE_CHILD_PROCESS = fake_child

            try:
                with self.assertRaises(SystemExit):
                    job_runner._handle_stop_signal(signal.SIGTERM, None)
            finally:
                job_runner._ACTIVE_CHILD_PROCESS = None

            fake_child.terminate.assert_called_once()
            fake_child.kill.assert_called_once()

    def test_stop_signal_handler_skips_already_dead_child(self) -> None:
        """If the child has already exited (race: SIGTERM arrives just
        after ``wait()`` returns), don't call ``terminate()`` on a
        zombie."""
        import web.operator_ui.job_runner as job_runner

        with tempfile.TemporaryDirectory() as tmp:
            job_dir = Path(tmp)
            job_runner._ACTIVE_JOB_DIR = job_dir
            fake_child = MagicMock()
            fake_child.poll.return_value = 0  # already exited
            job_runner._ACTIVE_CHILD_PROCESS = fake_child

            try:
                with self.assertRaises(SystemExit):
                    job_runner._handle_stop_signal(signal.SIGTERM, None)
            finally:
                job_runner._ACTIVE_CHILD_PROCESS = None

            fake_child.terminate.assert_not_called()
            fake_child.kill.assert_not_called()


if __name__ == "__main__":
    unittest.main()
