"""Walk-forward aggregate-level regression baseline test (audit FU-5).

Complements ``test_fold0_baseline`` (fold-0 backtest re-run). This
test runs the FULL walk-forward (all folds, ensemble, aggregate)
against a known-good config and asserts the headline aggregate
metrics stay within ±5% of the stored baseline.

The baseline is produced by ``scripts/generate_regression_baseline.py``.
Per the project's reference-data workflow ("I pull, you eyeball, you
sign off, I commit") the baseline JSON is NOT auto-generated by this
test — operators run the generator, review, and commit.

Skipped unless:

* ``RUN_E2E=1`` (the test is heavy — full walk-forward run).
* ``tests/regression/fixtures/walk_forward_baseline_metrics.json`` exists.
* ``tests/regression/fixtures/walk_forward_baseline_config.yaml`` exists
  OR a default ``config_walk.yaml`` is available at the project root
  with a usable ``provider_uri``.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
BASELINE_FIXTURE = FIXTURES_DIR / "walk_forward_baseline_metrics.json"
# Operators can drop a copy of the config used to generate the
# baseline next to the metrics fixture. If absent, the test falls
# back to ``config_walk.yaml`` at the project root.
BASELINE_CONFIG_FIXTURE = FIXTURES_DIR / "walk_forward_baseline_config.yaml"
PROJECT_ROOT = Path(__file__).resolve().parents[2]

# Headline metrics the test asserts on. Other aggregate keys (per-CI,
# bootstrap_seed, num_folds, etc.) are skipped via the ``keys``
# argument to :func:`compare_metrics`.
_HEADLINE_METRICS: tuple[str, ...] = (
    "mean_information_ratio",
    "mean_ic_1d",
    "mean_ic_5d",
    "mean_annualized_return",
    "worst_drawdown",
)


def _e2e_enabled() -> bool:
    # Single source of truth so every RUN_E2E gate accepts the same spellings.
    from tests.e2e_guard import run_e2e_enabled

    return run_e2e_enabled()


def _config_path() -> Path | None:
    """Resolve the YAML to use for the regression run. Prefer the
    fixture override (so the baseline + the test always agree); fall
    back to the project root ``config_walk.yaml``."""
    if BASELINE_CONFIG_FIXTURE.is_file():
        return BASELINE_CONFIG_FIXTURE
    fallback = PROJECT_ROOT / "config_walk.yaml"
    if fallback.is_file():
        return fallback
    return None


class WalkForwardAggregateBaselineTests(unittest.TestCase):
    """Re-run the full walk-forward and assert headline aggregates
    are within ±5% of the stored baseline."""

    def setUp(self) -> None:
        if not _e2e_enabled():
            self.skipTest(
                "RUN_E2E=1 not set — walk-forward regression baseline "
                "is heavy (full multi-fold backtest)."
            )
        if not BASELINE_FIXTURE.is_file():
            self.skipTest(
                f"Baseline fixture not found at {BASELINE_FIXTURE}. "
                "Generate it with "
                "``scripts/generate_regression_baseline.py``, then "
                "eyeball + commit per the reference-data workflow."
            )
        if _config_path() is None:
            self.skipTest(
                "No usable YAML found: neither "
                f"{BASELINE_CONFIG_FIXTURE} nor {PROJECT_ROOT}/config_walk.yaml."
            )

    def test_headline_aggregates_within_tolerance(self) -> None:
        # Late imports so the module can be IMPORTED on a no-qlib
        # machine without crashing — only the test body needs qlib.
        from scripts.run_walk_forward import _load_config
        from src.core.qlib_runtime import init_qlib_canonical
        from src.core.regression_baseline import compare_metrics
        from src.core.walk_forward import WalkForwardEngine

        config_path = _config_path()
        assert config_path is not None  # setUp guards this

        wf_config, qlib_config = _load_config(str(config_path))
        init_qlib_canonical(qlib_config)
        result = WalkForwardEngine.run(wf_config)

        with open(BASELINE_FIXTURE, encoding="utf-8") as fh:
            baseline_payload = json.load(fh)
        baseline_metrics = baseline_payload.get("aggregate_metrics", {})

        drifts = compare_metrics(
            actual=result.aggregate_metrics,
            baseline=baseline_metrics,
            tolerance=0.05,  # ±5% relative
            keys=_HEADLINE_METRICS,
        )
        if drifts:
            self.fail(
                "Walk-forward regression baseline drift exceeded ±5%:\n  - "
                + "\n  - ".join(drifts)
                + f"\n\nIf the drift is intentional (model change, bundle "
                f"refresh), re-run scripts/generate_regression_baseline.py "
                f"and commit the new {BASELINE_FIXTURE.name}."
            )


class WalkForwardAggregateBaselineFixtureSchemaTests(unittest.TestCase):
    """Schema-level validation of the baseline fixture — runs without
    RUN_E2E so the schema check still catches malformed baselines."""

    def setUp(self) -> None:
        if not BASELINE_FIXTURE.is_file():
            self.skipTest(f"Baseline fixture not found at {BASELINE_FIXTURE}.")

    def test_fixture_has_required_top_level_keys(self) -> None:
        with open(BASELINE_FIXTURE, encoding="utf-8") as fh:
            data = json.load(fh)
        for key in ("_provenance", "aggregate_metrics"):
            self.assertIn(key, data, f"baseline fixture missing key: {key}")

    def test_fixture_has_at_least_one_headline_metric(self) -> None:
        with open(BASELINE_FIXTURE, encoding="utf-8") as fh:
            data = json.load(fh)
        present = [
            k for k in _HEADLINE_METRICS
            if k in data.get("aggregate_metrics", {})
        ]
        self.assertGreater(
            len(present), 0,
            f"baseline carries none of the headline metrics "
            f"{_HEADLINE_METRICS!r} — regression test would skip all "
            "drift checks. Regenerate via "
            "scripts/generate_regression_baseline.py.",
        )

    def test_provenance_block_names_config_file(self) -> None:
        """Provenance should at minimum record what config produced
        the baseline (so future readers can tell whether the
        baseline applies to their run)."""
        with open(BASELINE_FIXTURE, encoding="utf-8") as fh:
            data = json.load(fh)
        prov = data.get("_provenance", {})
        self.assertIn(
            "config_file", prov,
            "baseline _provenance should record the config_file used; "
            "regenerate via the script if it's missing.",
        )


if __name__ == "__main__":
    unittest.main()
